<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChatHub.Core\ChatHub.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.WebSockets" Version="2.2.1" />
    <PackageReference Include="NATS.Client" Version="1.0.8" />
    <PackageReference Include="MongoDB.Driver" Version="2.24.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.7.27" />
    <PackageReference Include="AWSSDK.S3" Version="3.7.305" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.4.0" />
  </ItemGroup>

</Project>
